### ISSUE TITLE
NPE for drools 5.5.0.Final artefacts

### ISSUE THREAD

**Issue by pret79** [s4u/pgpverify-maven-plugin#8]
Hi,

Trying to scan some of the drools 5.5.0.Final artefacts leads to an NPE in the plugin (happens for the released 1.0 as well as the 1.1.0-SNAPSHOT version):

[DEBUG] Artifact file: /tmp/repo/org/drools/drools-decisiontables/5.5.0.Final/drools-decisiontables-5.5.0.Final.jar
[DEBUG] Artifact sign: /tmp/repo/org/drools/drools-decisiontables/5.5.0.Final/drools-decisiontables-5.5.0.Final.jar.asc
...
[ERROR] Failed to execute goal com.github.s4u.plugins:pgpverify-maven-plugin:1.1.0-SNAPSHOT:check (default-cli) on project XXXXXXXXXXXXXXXXXXX: Execution default-cli of goal com.github.s4u.plugins:pgpverify-maven-plugin:1.1.0-SNAPSHOT:check failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.s4u.plugins:pgpverify-maven-plugin:1.1.0-SNAPSHOT:check (default-cli) on project XXXXXXXXXXXXXXXXXXX: Execution default-cli of goal com.github.s4u.plugins:pgpverify-maven-plugin:1.1.0-SNAPSHOT:check failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.github.s4u.plugins:pgpverify-maven-plugin:1.1.0-SNAPSHOT:check failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.NullPointerException
        at com.github.s4u.plugins.PGPVerifyMojo.verifyPGPSignature(PGPVerifyMojo.java:305)
        at com.github.s4u.plugins.PGPVerifyMojo.execute(PGPVerifyMojo.java:181)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 20 more

The dependency that triggers the NPE:

<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-decisiontables</artifactId>
  <version>5.5.0.Final</version>
</dependency>

Greetings,
Markus

**Comment by pret79** [comment]
Forgot to mention that the "PGPSignature pgpSignature = sigList.get(0);" code triggers this NPE since the sigList variable is null. I've worked around this issue in my local checkout of the master branch so that my line numbers might be off..

**Comment by slawekjaranowski** [comment]
Can you give configuration of pgp-verify in your project.

Drools hasn't got signature ...
https://repo.maven.apache.org/maven2/org/drools/drools-decisiontables/5.5.0.Final/

**Comment by pret79** [comment]
Sure, my minimum pom.xml that triggers the error:
```
<?xml version="1.0" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
        <modelVersion>4.0.0</modelVersion>
        <groupId>test</groupId>
        <artifactId>test</artifactId>
        <packaging>jar</packaging>
        <version>1.0-SNAPSHOT</version>
        <dependencies>
                <dependency>
                        <groupId>org.drools</groupId>
                        <artifactId>drools-decisiontables</artifactId>
                        <version>5.5.0.Final</version>
                </dependency>
        </dependencies>
</project>
```

Maven command:
```
mvn clean install -Dpgpverify.keyserver=hkp://pool.sks-keyservers.net com.github.s4u.plugins:pgpverify-maven-plugin:1.0.0:check
```

**Comment by slawekjaranowski** [comment]
As you can see I prepared test for this case 
https://github.com/s4u/pgpverify-maven-plugin/commit/717fe9ad9bb4ff0f9af093b910b9e54d72a00142

And build OK https://travis-ci.org/s4u/pgpverify-maven-plugin/builds/61337670

**Comment by pret79** [comment]
Interesting.. I've just ran my pom.xml directly against Maven Central and it worked for me as well. Seems like my Sonatype Neuxs Maven Proxy is the troublemaker: It returns the following for the non-existing .asc file that matches the drools artefact:
```
<html>
<head>                                                                                                                                                  
<meta name="robots" content="noarchive" />                                                                                                              
<meta name="googlebot" content="nosnippet" />                                                                                                           
</head>                                                                                                                                                 
<body>
<div align=center>
<h3>Error. Page cannot be displayed. Please contact your service provider for more details.  (23)</h3>
</div>
</body>
</html>
```
I'll investigate this further..

**Comment by pret79** [comment]
In case you're interested in the root cause of this: The Pentaho repository contains the quoted 'PGP signature' from above:
http://repository.pentaho.org/content/groups/omni/org/drools/drools-decisiontables/5.5.0.Final/
Beside Central I also use Pentaho as one of the proxied repositories in my Nexus configuration.

Anyway, thank you for your help and the fix to not let the plugin die with an NPE any more :)

**Comment by slawekjaranowski** [comment]
Please remember that after my fix your check will fail if any of asc file has wrong content.
